
name: "Setup access to k8s cluster"
description: 'Uses 3 secrets to authenticate to google, GKE_SA_KEY can be shared by the organization'

inputs:
  GKE_CLUSTER:
    description: 'Name of the cluster'
    required: true
  GKE_ZONE:
    description: 'The zone of the cluster'
    required: true
  GKE_SA_KEY:
    description: 'Secret for k8s, shared as repository secret in Github'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Authenticate Google Cloud Platform
      id: 'auth'
      uses: google-github-actions/auth@v0.8.0
      with:
        credentials_json: ${{ inputs.GKE_SA_KEY }}

    - name: Authenticate Google Kubernetes Engine
      uses: google-github-actions/get-gke-credentials@v0.7.0
      with:
        cluster_name: ${{ inputs.GKE_CLUSTER }}
        location: ${{ inputs.GKE_ZONE }}
