#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: sbesnard
@File    :   csv_to_fidcCube.py
@Time    :   Mon Sep 26 10:47:17 2022
@Author  :   Simon Besnard
@Version :   1.0
@Contact :   besnard@gfz-potsdam.de
@License :   (C)Copyright 2022-2023, GFZ-Potsdam
@Desc    :   A method class for creating FIDC cube
"""
from typing import Any

import numpy as np
import pandas as pd
import xarray as xr
from datetime import datetime
from abc import ABC

DEFAULT_VARS = {"age",
                "agb",
                "agb_gapfilled",
                'canopy_height',                
                'canopy_height_gapfilled',
                'treecover2010',
                "AnnualMeanTemperature_WorlClim" ,
                "MeanDiurnalRange_WorlClim",
                "TemperatureSeasonality_WorlClim",
                "MaxTemperatureofWarmestMonth_WorlClim",
                "MinTemperatureofColdestMonth_WorlClim",
                "TemperatureAnnualRange_WorlClim",
                "MeanTemperatureofWettestQuarter_WorlClim",
                "MeanTemperatureofDriestQuarter_WorlClim" ,
                "MeanTemperatureofWarmestQuarter_WorlClim",
                "MeanTemperatureofColdestQuarter_WorlClim",        
                "Isothermality_WorlClim",
                "AnnualPrecipitation_WorlClim",
                "PrecipitationofWettestMonth_WorlClim",
                "PrecipitationofDriestMonth_WorlClim",
                "PrecipitationSeasonality_WorlClim",
                "PrecipitationofWettestQuarter_WorlClim",
                "PrecipitationofDriestQuarter_WorlClim",
                "PrecipitationofWarmestQuarter_WorlClim", 
                "PrecipitationofColdestQuarter_WorlClim",
                "AnnualSrad_WorlClim",
                "AnnualWind_WorlClim",
                "AnnualVapr_WorlClim",
                'prec.mon.01_WorlClim',
                'prec.mon.02_WorlClim',
                'prec.mon.03_WorlClim',
                'prec.mon.04_WorlClim',
                'prec.mon.05_WorlClim',
                'prec.mon.06_WorlClim',
                'prec.mon.07_WorlClim',
                'prec.mon.08_WorlClim',
                'prec.mon.09_WorlClim',
                'prec.mon.10_WorlClim',
                'prec.mon.11_WorlClim',
                'prec.mon.12_WorlClim',
                "srad.mon.01_WorlClim",
                "srad.mon.02_WorlClim",
                "srad.mon.03_WorlClim",
                "srad.mon.04_WorlClim",
                "srad.mon.05_WorlClim",
                "srad.mon.06_WorlClim",
                "srad.mon.07_WorlClim",
                "srad.mon.08_WorlClim",
                "srad.mon.09_WorlClim",
                "srad.mon.10_WorlClim",
                "srad.mon.11_WorlClim",
                "srad.mon.12_WorlClim",
                'tmax.mon.01_WorlClim',
                'tmax.mon.02_WorlClim',
                'tmax.mon.03_WorlClim',
                'tmax.mon.04_WorlClim',
                'tmax.mon.05_WorlClim',
                'tmax.mon.06_WorlClim',
                'tmax.mon.07_WorlClim',
                'tmax.mon.08_WorlClim',
                'tmax.mon.09_WorlClim',
                'tmax.mon.10_WorlClim',
                'tmax.mon.11_WorlClim',
                'tmax.mon.12_WorlClim',
                'tmean.mon.01_WorlClim',
                'tmean.mon.02_WorlClim',
                'tmean.mon.03_WorlClim',
                'tmean.mon.04_WorlClim',
                'tmean.mon.05_WorlClim',
                'tmean.mon.06_WorlClim',
                'tmean.mon.07_WorlClim',
                'tmean.mon.08_WorlClim',
                'tmean.mon.09_WorlClim',
                'tmean.mon.10_WorlClim',
                'tmean.mon.11_WorlClim',
                'tmean.mon.12_WorlClim',
                'tmin.mon.01_WorlClim',
                'tmin.mon.02_WorlClim',
                'tmin.mon.03_WorlClim',
                'tmin.mon.04_WorlClim',
                'tmin.mon.05_WorlClim',
                'tmin.mon.06_WorlClim',
                'tmin.mon.07_WorlClim',
                'tmin.mon.08_WorlClim',
                'tmin.mon.09_WorlClim',
                'tmin.mon.10_WorlClim',
                'tmin.mon.11_WorlClim',
                'tmin.mon.12_WorlClim',
                'vapr.mon.01_WorlClim',
                'vapr.mon.02_WorlClim',
                'vapr.mon.03_WorlClim',
                'vapr.mon.04_WorlClim',
                'vapr.mon.05_WorlClim',
                'vapr.mon.06_WorlClim',
                'vapr.mon.07_WorlClim',
                'vapr.mon.08_WorlClim',
                'vapr.mon.09_WorlClim',
                'vapr.mon.10_WorlClim',
                'vapr.mon.11_WorlClim',
                'vapr.mon.12_WorlClim',
                'wind.mon.01_WorlClim',
                'wind.mon.02_WorlClim',
                'wind.mon.03_WorlClim',
                'wind.mon.04_WorlClim',
                'wind.mon.05_WorlClim',
                'wind.mon.06_WorlClim',
                'wind.mon.07_WorlClim',
                'wind.mon.08_WorlClim',
                'wind.mon.09_WorlClim',
                'wind.mon.10_WorlClim',
                'wind.mon.11_WorlClim',
                'wind.mon.12_WorlClim',                
                'bdod_0_5cm_mean',
                'bdod_5_15cm_mean',
                'bdod_15_30cm_mean',
                'bdod_30_60cm_mean',
                'bdod_60_100cm_mean',
                'bdod_100_200cm_mean',
                'cec_0_5cm_mean',
                'cec_5_15cm_mean',
                'cec_15_30cm_mean',
                'cec_30_60cm_mean',
                'cec_60_100cm_mean',
                'cec_100_200cm_mean',
                'cfvo_0_5cm_mean',
                'cfvo_5_15cm_mean',
                'cfvo_15_30cm_mean',
                'cfvo_30_60cm_mean',
                'cfvo_60_100cm_mean',
                'cfvo_100_200cm_mean',
                'clay_0_5cm_mean',
                'clay_5_15cm_mean',
                'clay_15_30cm_mean',
                'clay_30_60cm_mean',
                'clay_60_100cm_mean',
                'clay_100_200cm_mean',
                'nitrogen_0_5cm_mean',
                'nitrogen_5_15cm_mean',
                'nitrogen_15_30cm_mean',
                'nitrogen_30_60cm_mean',
                'nitrogen_60_100cm_mean',
                'nitrogen_100_200cm_mean',
                'phh2o_0_5cm_mean',
                'phh2o_5_15cm_mean',
                'phh2o_15_30cm_mean',
                'phh2o_30_60cm_mean',
                'phh2o_60_100cm_mean',
                'phh2o_100_200cm_mean',
                'sand_0_5cm_mean',
                'sand_5_15cm_mean',
                'sand_15_30cm_mean',
                'sand_30_60cm_mean',
                'sand_60_100cm_mean',
                'sand_100_200cm_mean',
                'silt_0_5cm_mean',
                'silt_5_15cm_mean',
                'silt_15_30cm_mean',
                'silt_30_60cm_mean',
                'silt_60_100cm_mean',
                'silt_100_200cm_mean',
                'soc_0_5cm_mean',
                'soc_5_15cm_mean',
                'soc_15_30cm_mean',
                'soc_30_60cm_mean',
                'soc_60_100cm_mean',
                'soc_100_200cm_mean',
                'ocd_0_5cm_mean',
                'ocd_5_15cm_mean',
                'ocd_15_30cm_mean',
                'ocd_30_60cm_mean',
                'ocd_60_100cm_mean',
                'ocd_100_200cm_mean',
                'bdod_0_5cm_mean_1000',
                'bdod_5_15cm_mean_1000',
                'bdod_15_30cm_mean_1000',
                'bdod_30_60cm_mean_1000',
                'bdod_60_100cm_mean_1000',
                'bdod_100_200cm_mean_1000',
                'cec_0_5cm_mean_1000',
                'cec_5_15cm_mean_1000',
                'cec_15_30cm_mean_1000',
                'cec_30_60cm_mean_1000',
                'cec_60_100cm_mean_1000',
                'cec_100_200cm_mean_1000',
                'cfvo_0_5cm_mean_1000',
                'cfvo_5_15cm_mean_1000',
                'cfvo_15_30cm_mean_1000',
                'cfvo_30_60cm_mean_1000',
                'cfvo_60_100cm_mean_1000',
                'cfvo_100_200cm_mean_1000',
                'clay_0_5cm_mean_1000',
                'clay_5_15cm_mean_1000',
                'clay_15_30cm_mean_1000',
                'clay_30_60cm_mean_1000',
                'clay_60_100cm_mean_1000',
                'clay_100_200cm_mean_1000',
                'nitrogen_0_5cm_mean_1000',
                'nitrogen_5_15cm_mean_1000',
                'nitrogen_15_30cm_mean_1000',
                'nitrogen_30_60cm_mean_1000',
                'nitrogen_60_100cm_mean_1000',
                'nitrogen_100_200cm_mean_1000',
                'phh2o_0_5cm_mean_1000',
                'phh2o_5_15cm_mean_1000',
                'phh2o_15_30cm_mean_1000',
                'phh2o_30_60cm_mean_1000',
                'phh2o_60_100cm_mean_1000',
                'phh2o_100_200cm_mean_1000',
                'sand_0_5cm_mean_1000',
                'sand_5_15cm_mean_1000',
                'sand_15_30cm_mean_1000',
                'sand_30_60cm_mean_1000',
                'sand_60_100cm_mean_1000',
                'sand_100_200cm_mean_1000',
                'silt_0_5cm_mean_1000',
                'silt_5_15cm_mean_1000',
                'silt_15_30cm_mean_1000',
                'silt_30_60cm_mean_1000',
                'silt_60_100cm_mean_1000',
                'silt_100_200cm_mean_1000',
                'soc_0_5cm_mean_1000',
                'soc_5_15cm_mean_1000',
                'soc_15_30cm_mean_1000',
                'soc_30_60cm_mean_1000',
                'soc_60_100cm_mean_1000',
                'soc_100_200cm_mean_1000',
                'ocd_0_5cm_mean_1000',
                'ocd_5_15cm_mean_1000',
                'ocd_15_30cm_mean_1000',
                'ocd_30_60cm_mean_1000',
                'ocd_60_100cm_mean_1000',
                'ocd_100_200cm_mean_1000',
                
                }
    
DEFAULT_LONG_NAMES = {
        "age"  : "forest age at plot level",
        "agb"  : "above-ground biomass",
        "agb_gapfilled": "above-ground biomass gapfilled with ESA-CCI biomass",
        'canopy_height': 'Canopy height',
        'canopy_height_gapfilled': 'Canopy height gapfilled with RS data',
        'treecover2010': 'Hansen tree cover 2010',
        "AnnualMeanTemperature_WorlClim" : "Annual Mean Temperature - worldclim dataset",
        "MeanDiurnalRange_WorlClim" : " Mean Diurnal Range (Mean of monthly (max temp - min temp)) - worldclim dataset",
        "TemperatureSeasonality_WorlClim" : "Temperature Seasonality (standard deviation *100) - worldclim dataset",
        "MaxTemperatureofWarmestMonth_WorlClim" : "Max Temperature of Warmest Month - worldclim dataset",
        "MinTemperatureofColdestMonth_WorlClim" : "Min Temperature of Coldest Month - worldclim dataset",
        "TemperatureAnnualRange_WorlClim" :  "Temperature Annual Range (MaxTemperatureofWarmestMonth - MinTemperatureofColdestMonth) - worldclim dataset",
        "MeanTemperatureofWettestQuarter_WorlClim" : "Mean Temperature of Wettest Quarter - worldclim dataset",
        "MeanTemperatureofDriestQuarter_WorlClim"  : "Mean Temperature of Driest Quarter - worldclim dataset",
        "MeanTemperatureofWarmestQuarter_WorlClim" : "Mean Temperature of Warmest Quarter - worldclim dataset",
        "MeanTemperatureofColdestQuarter_WorlClim" : " Mean Temperature of Coldest Quarter - worldclim dataset",        
        "Isothermality_WorlClim" : "Isothermality (MeanDiurnalRange - TemperatureAnnualRange) *100 - worldclim dataset",
        "AnnualPrecipitation_WorlClim" : "Annual Precipitation - worldclim dataset",
        "PrecipitationofWettestMonth_WorlClim"  : "Precipitation of Wettest Month - worldclim dataset",
        "PrecipitationofDriestMonth_WorlClim" :  "Precipitation of Driest Month - worldclim dataset",
        "PrecipitationSeasonality_WorlClim" : "Precipitation Seasonality (Coefficient of Variation) - worldclim dataset",
        "PrecipitationofWettestQuarter_WorlClim" : "Precipitation of Wettest Quarter - worldclim dataset",
        "PrecipitationofDriestQuarter_WorlClim" : "Precipitation of Driest Quarter - worldclim dataset",
        "PrecipitationofWarmestQuarter_WorlClim" : "Precipitation of Warmest Quarter - worldclim dataset", 
        "PrecipitationofColdestQuarter_WorlClim" : "Precipitation of Coldest Quarter - worldclim dataset",
        "AnnualSrad_WorlClim" : "Annual Mean solar radiation - worldclim dataset",
        "AnnualWind_WorlClim" : "Annual Mean wind speed - worldclim dataset",
        "AnnualVapr_WorlClim" : "Annual Mean water vapor pressure - worldclim dataset",
        'prec.mon.01_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.02_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.03_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.04_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.05_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.06_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.07_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.08_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.09_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.10_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.11_WorlClim' : "Monthly Precipitation - worldclim dataset",
        'prec.mon.12_WorlClim' : "Monthly Precipitation - worldclim dataset",
        "srad.mon.01_WorlClim" : "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.02_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.03_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.04_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.05_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.06_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.07_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.08_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.09_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.10_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.11_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        "srad.mon.12_WorlClim": "Monthly Mean solar radiation - worldclim dataset",
        'tmax.mon.01_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.02_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.03_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.04_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.05_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.06_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.07_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.08_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.09_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.10_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.11_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmax.mon.12_WorlClim' : "Monthly Max Temperature - worldclim dataset",
        'tmean.mon.01_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.02_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.03_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.04_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.05_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.06_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.07_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.08_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.09_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.10_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.11_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmean.mon.12_WorlClim' : "Monthly Mean Temperature - worldclim dataset",
        'tmin.mon.01_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.02_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.03_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.04_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.05_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.06_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.07_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.08_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.09_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.10_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.11_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'tmin.mon.12_WorlClim' : "Monthly Min Temperature - worldclim dataset",
        'vapr.mon.01_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.02_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.03_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.04_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.05_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.06_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.07_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.08_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.09_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.10_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.11_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'vapr.mon.12_WorlClim' : "Monthly Mean water vapor pressure - worldclim dataset",
        'wind.mon.01_WorlClim' : "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.02_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.03_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.04_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.05_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.06_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.07_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.08_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.09_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.10_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.11_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'wind.mon.12_WorlClim': "Monthly Mean wind speed - worldclim dataset",
        'bdod_0_5cm_mean': 'Bulk density of the fine earth fraction - 0 to 5cm soil layers',
        'bdod_5_15cm_mean': 'Bulk density of the fine earth fraction - 5 to 15cm soil layers',
        'bdod_15_30cm_mean': 'Bulk density of the fine earth fraction - 15 to 30cm soil layers',
        'bdod_30_60cm_mean': 'Bulk density of the fine earth fraction - 30 to 6cm soil layers',
        'bdod_60_100cm_mean': 'Bulk density of the fine earth fraction - 60 to 10cm soil layers',
        'bdod_100_200cm_mean': 'Bulk density of the fine earth fraction - 100 to 200cm soil layers',
        'cec_0_5cm_mean': 'Cation Exchange Capacity of the soil - 0 to 5cm soil layers',
        'cec_5_15cm_mean': 'Cation Exchange Capacity of the soil - 5 to 15cm soil layers',
        'cec_15_30cm_mean': 'Cation Exchange Capacity of the soil - 15 to 30cm soil layers',
        'cec_30_60cm_mean': 'Cation Exchange Capacity of the soil - 30 to 6cm soil layers',
        'cec_60_100cm_mean': 'Cation Exchange Capacity of the soil - 60 to 10cm soil layers',
        'cec_100_200cm_mean': 'Cation Exchange Capacity of the soil - 100 to 200cm soil layers',
        'cfvo_0_5cm_mean': 'Volumetric fraction of coarse fragments (> 2 mm) - 0 to 5cm soil layers',
        'cfvo_5_15cm_mean': 'Volumetric fraction of coarse fragments (> 2 mm) - 5 to 15cm soil layers',
        'cfvo_15_30cm_mean': 'Volumetric fraction of coarse fragments (> 2 mm) - 15 to 30cm soil layers',
        'cfvo_30_60cm_mean': 'Volumetric fraction of coarse fragments (> 2 mm) - 30 to 6cm soil layers',
        'cfvo_60_100cm_mean': 'Volumetric fraction of coarse fragments (> 2 mm) - 60 to 10cm soil layers',
        'cfvo_100_200cm_mean': 'Volumetric fraction of coarse fragments (> 2 mm) - 100 to 200cm soil layers',
        'clay_0_5cm_mean': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 0 to 5cm soil layers',
        'clay_5_15cm_mean': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction) - 5 to 15cm soil layers',
        'clay_15_30cm_mean': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 15 to 30cm soil layers',
        'clay_30_60cm_mean': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 30 to 6cm soil layers',
        'clay_60_100cm_mean': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 60 to 10cm soil layers',
        'clay_100_200cm_mean': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 100 to 200cm soil layers',
        'nitrogen_0_5cm_mean': 'Total nitrogen (N) - 0 to 5cm soil layers',
        'nitrogen_5_15cm_mean': 'Total nitrogen (N) - 5 to 15cm soil layers',
        'nitrogen_15_30cm_mean': 'Total nitrogen (N) - 15 to 30cm soil layers',
        'nitrogen_30_60cm_mean': 'Total nitrogen (N) - 30 to 6cm soil layers',
        'nitrogen_60_100cm_mean': 'Total nitrogen (N) - 60 to 10cm soil layers',
        'nitrogen_100_200cm_mean': 'Total nitrogen (N) - 100 to 200cm soil layers',
        'phh2o_0_5cm_mean': 'Soil pH - 0 to 5cm soil layers',
        'phh2o_5_15cm_mean': 'Soil pH - 5 to 15cm soil layers',
        'phh2o_15_30cm_mean': 'Soil pH - 15 to 30cm soil layers',
        'phh2o_30_60cm_mean': 'Soil pH - 30 to 6cm soil layers',
        'phh2o_60_100cm_mean': 'Soil pH - 60 to 10cm soil layers',
        'phh2o_100_200cm_mean': 'Soil pH - 100 to 200cm soil layers',
        'sand_0_5cm_mean': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 0 to 5cm soil layers',
        'sand_5_15cm_mean': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 5 to 15cm soil layers',
        'sand_15_30cm_mean': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 15 to 30cm soil layers',
        'sand_30_60cm_mean': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 30 to 6cm soil layers',
        'sand_60_100cm_mean': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 60 to 10cm soil layers',
        'sand_100_200cm_mean': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 100 to 200cm soil layers',
        'silt_0_5cm_mean': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 0 to 5cm soil layers',
        'silt_5_15cm_mean': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 5 to 15cm soil layers',
        'silt_15_30cm_mean': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 15 to 30cm soil layers',
        'silt_30_60cm_mean': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 30 to 6cm soil layers',
        'silt_60_100cm_mean': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 60 to 10cm soil layers',
        'silt_100_200cm_mean': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 100 to 200cm soil layers',
        'soc_0_5cm_mean': 'Soil organic carbon content in the fine earth fraction - 0 to 5cm soil layers',
        'soc_5_15cm_mean': 'Soil organic carbon content in the fine earth fraction - 5 to 15cm soil layers',
        'soc_15_30cm_mean': 'Soil organic carbon content in the fine earth fraction - 15 to 30cm soil layers',
        'soc_30_60cm_mean': 'Soil organic carbon content in the fine earth fraction - 30 to 6cm soil layers',
        'soc_60_100cm_mean': 'Soil organic carbon content in the fine earth fraction - 60 to 10cm soil layers',
        'soc_100_200cm_mean': 'Soil organic carbon content in the fine earth fraction - 100 to 200cm soil layers',
        'ocd_0_5cm_mean': 'Organic carbon density - 0 to 5cm soil layers',
        'ocd_5_15cm_mean': 'Organic carbon density - 5 to 15cm soil layers',
        'ocd_15_30cm_mean': 'Organic carbon density - 15 to 30cm soil layers',
        'ocd_30_60cm_mean': 'Organic carbon density - 30 to 6cm soil layers',
        'ocd_60_100cm_mean': 'Organic carbon density - 60 to 10cm soil layers',
        'ocd_100_200cm_mean': 'Organic carbon density - 100 to 200cm soil layers',
        'bdod_0_5cm_mean_1000': 'Bulk density of the fine earth fraction - 0 to 5cm soil layers',
        'bdod_5_15cm_mean_1000': 'Bulk density of the fine earth fraction - 5 to 15cm soil layers',
        'bdod_15_30cm_mean_1000': 'Bulk density of the fine earth fraction - 15 to 30cm soil layers',
        'bdod_30_60cm_mean_1000': 'Bulk density of the fine earth fraction - 30 to 6cm soil layers',
        'bdod_60_100cm_mean_1000': 'Bulk density of the fine earth fraction - 60 to 10cm soil layers',
        'bdod_100_200cm_mean_1000': 'Bulk density of the fine earth fraction - 100 to 200cm soil layers',
        'cec_0_5cm_mean_1000': 'Cation Exchange Capacity of the soil - 0 to 5cm soil layers',
        'cec_5_15cm_mean_1000': 'Cation Exchange Capacity of the soil - 5 to 15cm soil layers',
        'cec_15_30cm_mean_1000': 'Cation Exchange Capacity of the soil - 15 to 30cm soil layers',
        'cec_30_60cm_mean_1000': 'Cation Exchange Capacity of the soil - 30 to 6cm soil layers',
        'cec_60_100cm_mean_1000': 'Cation Exchange Capacity of the soil - 60 to 10cm soil layers',
        'cec_100_200cm_mean_1000': 'Cation Exchange Capacity of the soil - 100 to 200cm soil layers',
        'cfvo_0_5cm_mean_1000': 'Volumetric fraction of coarse fragments (> 2 mm) - 0 to 5cm soil layers',
        'cfvo_5_15cm_mean_1000': 'Volumetric fraction of coarse fragments (> 2 mm) - 5 to 15cm soil layers',
        'cfvo_15_30cm_mean_1000': 'Volumetric fraction of coarse fragments (> 2 mm) - 15 to 30cm soil layers',
        'cfvo_30_60cm_mean_1000': 'Volumetric fraction of coarse fragments (> 2 mm) - 30 to 6cm soil layers',
        'cfvo_60_100cm_mean_1000': 'Volumetric fraction of coarse fragments (> 2 mm) - 60 to 10cm soil layers',
        'cfvo_100_200cm_mean_1000': 'Volumetric fraction of coarse fragments (> 2 mm) - 100 to 200cm soil layers',
        'clay_0_5cm_mean_1000': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 0 to 5cm soil layers',
        'clay_5_15cm_mean_1000': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction) - 5 to 15cm soil layers',
        'clay_15_30cm_mean_1000': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 15 to 30cm soil layers',
        'clay_30_60cm_mean_1000': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 30 to 6cm soil layers',
        'clay_60_100cm_mean_1000': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 60 to 10cm soil layers',
        'clay_100_200cm_mean_1000': 'Proportion of clay particles (< 0.002 mm) in the fine earth fraction - 100 to 200cm soil layers',
        'nitrogen_0_5cm_mean_1000': 'Total nitrogen (N) - 0 to 5cm soil layers',
        'nitrogen_5_15cm_mean_1000': 'Total nitrogen (N) - 5 to 15cm soil layers',
        'nitrogen_15_30cm_mean_1000': 'Total nitrogen (N) - 15 to 30cm soil layers',
        'nitrogen_30_60cm_mean_1000': 'Total nitrogen (N) - 30 to 6cm soil layers',
        'nitrogen_60_100cm_mean_1000': 'Total nitrogen (N) - 60 to 10cm soil layers',
        'nitrogen_100_200cm_mean_1000': 'Total nitrogen (N) - 100 to 200cm soil layers',
        'phh2o_0_5cm_mean_1000': 'Soil pH - 0 to 5cm soil layers',
        'phh2o_5_15cm_mean_1000': 'Soil pH - 5 to 15cm soil layers',
        'phh2o_15_30cm_mean_1000': 'Soil pH - 15 to 30cm soil layers',
        'phh2o_30_60cm_mean_1000': 'Soil pH - 30 to 6cm soil layers',
        'phh2o_60_100cm_mean_1000': 'Soil pH - 60 to 10cm soil layers',
        'phh2o_100_200cm_mean_1000': 'Soil pH - 100 to 200cm soil layers',
        'sand_0_5cm_mean_1000': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 0 to 5cm soil layers',
        'sand_5_15cm_mean_1000': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 5 to 15cm soil layers',
        'sand_15_30cm_mean_1000': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 15 to 30cm soil layers',
        'sand_30_60cm_mean_1000': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 30 to 6cm soil layers',
        'sand_60_100cm_mean_1000': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 60 to 10cm soil layers',
        'sand_100_200cm_mean_1000': 'Proportion of sand particles (> 0.05 mm) in the fine earth fraction - 100 to 200cm soil layers',
        'silt_0_5cm_mean_1000': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 0 to 5cm soil layers',
        'silt_5_15cm_mean_1000': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 5 to 15cm soil layers',
        'silt_15_30cm_mean_1000': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 15 to 30cm soil layers',
        'silt_30_60cm_mean_1000': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 30 to 6cm soil layers',
        'silt_60_100cm_mean_1000': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 60 to 10cm soil layers',
        'silt_100_200cm_mean_1000': 'Proportion of silt particles (> 0.05 mm) in the fine earth fraction - 100 to 200cm soil layers',
        'soc_0_5cm_mean_1000': 'Soil organic carbon content in the fine earth fraction - 0 to 5cm soil layers',
        'soc_5_15cm_mean_1000': 'Soil organic carbon content in the fine earth fraction - 5 to 15cm soil layers',
        'soc_15_30cm_mean_1000': 'Soil organic carbon content in the fine earth fraction - 15 to 30cm soil layers',
        'soc_30_60cm_mean_1000': 'Soil organic carbon content in the fine earth fraction - 30 to 6cm soil layers',
        'soc_60_100cm_mean_1000': 'Soil organic carbon content in the fine earth fraction - 60 to 10cm soil layers',
        'soc_100_200cm_mean_1000': 'Soil organic carbon content in the fine earth fraction - 100 to 200cm soil layers',
        'ocd_0_5cm_mean_1000': 'Organic carbon density - 0 to 5cm soil layers',
        'ocd_5_15cm_mean_1000': 'Organic carbon density - 5 to 15cm soil layers',
        'ocd_15_30cm_mean_1000': 'Organic carbon density - 15 to 30cm soil layers',
        'ocd_30_60cm_mean_1000': 'Organic carbon density - 30 to 6cm soil layers',
        'ocd_60_100cm_mean_1000': 'Organic carbon density - 60 to 10cm soil layers',
        'ocd_100_200cm_mean_1000': 'Organic carbon density - 100 to 200cm soil layers',
        }

DEFAULT_UNITS = {"age"  : "years",
        "agb"  : "Mg ha-1",
        "agb_gapfilled"  : "Mg ha-1",
        'canopy_height': 'meters', 
        'canopy_height_gapfilled': 'meters',
        'treecover2010': 'Percentage',
        "AnnualMeanTemperature_WorlClim" : "deg C",
        "MeanDiurnalRange_WorlClim" : "deg C",
        "TemperatureSeasonality_WorlClim" : "deg C", 
        "MaxTemperatureofWarmestMonth_WorlClim" : "deg C",
        "MinTemperatureofColdestMonth_WorlClim" : "deg C",
        "TemperatureAnnualRange_WorlClim" :  "deg C",
        "MeanTemperatureofWettestQuarter_WorlClim" : "deg C",
        "MeanTemperatureofDriestQuarter_WorlClim"  : "deg C",
        "MeanTemperatureofWarmestQuarter_WorlClim" : "deg C",
        "MeanTemperatureofColdestQuarter_WorlClim" : "deg C",        
        "Isothermality_WorlClim" : "deg C",
        "AnnualPrecipitation_WorlClim" : "mm",
        "PrecipitationofWettestMonth_WorlClim"  : "mm",
        "PrecipitationofDriestMonth_WorlClim" :  "mm",
        "PrecipitationSeasonality_WorlClim" : "mm",
        "PrecipitationofWettestQuarter_WorlClim" : "mm",
        "PrecipitationofDriestQuarter_WorlClim" : "mm",
        "PrecipitationofWarmestQuarter_WorlClim" : "mm", 
        "PrecipitationofColdestQuarter_WorlClim" : "mm",
        "AnnualSrad_WorlClim" : "W m-2",
        "AnnualWind_WorlClim" : "m s-1",        
        "AnnualVapr_WorlClim" : "hPa",
        'prec.mon.01_WorlClim': "mm",
        'prec.mon.02_WorlClim': "mm",
        'prec.mon.03_WorlClim': "mm",
        'prec.mon.04_WorlClim': "mm",
        'prec.mon.05_WorlClim': "mm",
        'prec.mon.06_WorlClim': "mm",
        'prec.mon.07_WorlClim': "mm",
        'prec.mon.08_WorlClim': "mm",
        'prec.mon.09_WorlClim': "mm",
        'prec.mon.10_WorlClim': "mm",
        'prec.mon.11_WorlClim': "mm",
        'prec.mon.12_WorlClim': "mm",
        "srad.mon.01_WorlClim": "W m-2",
        "srad.mon.02_WorlClim": "W m-2",
        "srad.mon.03_WorlClim": "W m-2",
        "srad.mon.04_WorlClim": "W m-2",
        "srad.mon.05_WorlClim": "W m-2",
        "srad.mon.06_WorlClim": "W m-2",
        "srad.mon.07_WorlClim": "W m-2",
        "srad.mon.08_WorlClim": "W m-2",
        "srad.mon.09_WorlClim": "W m-2",
        "srad.mon.10_WorlClim": "W m-2",
        "srad.mon.11_WorlClim": "W m-2",
        "srad.mon.12_WorlClim": "W m-2",
        'tmax.mon.01_WorlClim' :  "deg C",
        'tmax.mon.02_WorlClim' :  "deg C",
        'tmax.mon.03_WorlClim' :  "deg C",
        'tmax.mon.04_WorlClim' :  "deg C",
        'tmax.mon.05_WorlClim' :  "deg C",
        'tmax.mon.06_WorlClim' :  "deg C",
        'tmax.mon.07_WorlClim' :  "deg C",
        'tmax.mon.08_WorlClim' :  "deg C",
        'tmax.mon.09_WorlClim' :  "deg C",
        'tmax.mon.10_WorlClim' :  "deg C",
        'tmax.mon.11_WorlClim' :  "deg C",
        'tmax.mon.12_WorlClim' :  "deg C",
        'tmean.mon.01_WorlClim' :  "deg C",
        'tmean.mon.02_WorlClim' :  "deg C",
        'tmean.mon.03_WorlClim' :  "deg C",
        'tmean.mon.04_WorlClim' :  "deg C",
        'tmean.mon.05_WorlClim' :  "deg C",
        'tmean.mon.06_WorlClim' :  "deg C",
        'tmean.mon.07_WorlClim' :  "deg C",
        'tmean.mon.08_WorlClim' :  "deg C",
        'tmean.mon.09_WorlClim' :  "deg C",
        'tmean.mon.10_WorlClim' :  "deg C",
        'tmean.mon.11_WorlClim' :  "deg C",
        'tmean.mon.12_WorlClim' :  "deg C",
        'tmin.mon.01_WorlClim' :  "deg C",
        'tmin.mon.02_WorlClim' :  "deg C",
        'tmin.mon.03_WorlClim' :  "deg C",
        'tmin.mon.04_WorlClim' :  "deg C",
        'tmin.mon.05_WorlClim' :  "deg C",
        'tmin.mon.06_WorlClim' :  "deg C",
        'tmin.mon.07_WorlClim' :  "deg C",
        'tmin.mon.08_WorlClim' :  "deg C",
        'tmin.mon.09_WorlClim' :  "deg C",
        'tmin.mon.10_WorlClim' :  "deg C",
        'tmin.mon.11_WorlClim' :  "deg C",
        'tmin.mon.12_WorlClim' :  "deg C",
        'vapr.mon.01_WorlClim' : "hPa",
        'vapr.mon.02_WorlClim' : "hPa",
        'vapr.mon.03_WorlClim' : "hPa",
        'vapr.mon.04_WorlClim' : "hPa",
        'vapr.mon.05_WorlClim' : "hPa",
        'vapr.mon.06_WorlClim' : "hPa",
        'vapr.mon.07_WorlClim' : "hPa",
        'vapr.mon.08_WorlClim' : "hPa",
        'vapr.mon.09_WorlClim' : "hPa",
        'vapr.mon.10_WorlClim' : "hPa",
        'vapr.mon.11_WorlClim' : "hPa",
        'vapr.mon.12_WorlClim' : "hPa",
        'wind.mon.01_WorlClim' : "m s-1", 
        'wind.mon.02_WorlClim' : "m s-1", 
        'wind.mon.03_WorlClim' : "m s-1", 
        'wind.mon.04_WorlClim' : "m s-1", 
        'wind.mon.05_WorlClim' : "m s-1", 
        'wind.mon.06_WorlClim' : "m s-1", 
        'wind.mon.07_WorlClim' : "m s-1", 
        'wind.mon.08_WorlClim' : "m s-1", 
        'wind.mon.09_WorlClim' : "m s-1", 
        'wind.mon.10_WorlClim' : "m s-1", 
        'wind.mon.11_WorlClim' : "m s-1", 
        'wind.mon.12_WorlClim' : "m s-1",        
        'bdod_0_5cm_mean': 'cg/cm3',
        'bdod_5_15cm_mean': 'cg/cm3',
        'bdod_15_30cm_mean': 'cg/cm3',
        'bdod_30_60cm_mean': 'cg/cm3',
        'bdod_60_100cm_mean': 'cg/cm3',
        'bdod_100_200cm_mean': 'cg/cm3',
        'cec_0_5cm_mean': 'mmol/kg',
        'cec_5_15cm_mean': 'mmol/kg',
        'cec_15_30cm_mean': 'mmol/kg',
        'cec_30_60cm_mean': 'mmol/kg',
        'cec_60_100cm_mean': 'mmol/kg',
        'cec_100_200cm_mean': 'cm3/dm3 (vol‰)',
        'cfvo_0_5cm_mean': 'cm3/dm3 (vol‰)',
        'cfvo_5_15cm_mean': 'cm3/dm3 (vol‰)',
        'cfvo_15_30cm_mean': 'cm3/dm3 (vol‰)',
        'cfvo_30_60cm_mean': 'cm3/dm3 (vol‰)',
        'cfvo_60_100cm_mean': 'cm3/dm3 (vol‰)',
        'cfvo_100_200cm_mean': 'cm3/dm3 (vol‰)',
        'clay_0_5cm_mean': 'g/kg',
        'clay_5_15cm_mean': 'g/kg',
        'clay_15_30cm_mean': 'g/kg',
        'clay_30_60cm_mean': 'g/kg',
        'clay_60_100cm_mean': 'g/kg',
        'clay_100_200cm_mean': 'g/kg',
        'nitrogen_0_5cm_mean': 'cg/kg',
        'nitrogen_5_15cm_mean': 'cg/kg',
        'nitrogen_15_30cm_mean': 'cg/kg',
        'nitrogen_30_60cm_mean': 'cg/kg',
        'nitrogen_60_100cm_mean': 'cg/kg',
        'nitrogen_100_200cm_mean': 'cg/kg',
        'phh2o_0_5cm_mean': 'pHx10',
        'phh2o_5_15cm_mean': 'pHx10',
        'phh2o_15_30cm_mean': 'pHx10',
        'phh2o_30_60cm_mean': 'pHx10',
        'phh2o_60_100cm_mean': 'pHx10',
        'phh2o_100_200cm_mean': 'pHx10',
        'sand_0_5cm_mean': 'g/kg',
        'sand_5_15cm_mean': 'g/kg',
        'sand_15_30cm_mean': 'g/kg',
        'sand_30_60cm_mean': 'g/kg',
        'sand_60_100cm_mean': 'g/kg',
        'sand_100_200cm_mean': 'g/kg',
        'silt_0_5cm_mean': 'g/kg',
        'silt_5_15cm_mean': 'g/kg',
        'silt_15_30cm_mean': 'g/kg',
        'silt_30_60cm_mean': 'g/kg',
        'silt_60_100cm_mean': 'g/kg',
        'silt_100_200cm_mean': 'g/kg',
        'soc_0_5cm_mean': 'dg/kg',
        'soc_5_15cm_mean': 'dg/kg',
        'soc_15_30cm_mean': 'dg/kg',
        'soc_30_60cm_mean': 'dg/kg',
        'soc_60_100cm_mean': 'dg/kg',
        'soc_100_200cm_mean': 'dg/kg',
        'ocd_0_5cm_mean': 'hg/dm^3',
        'ocd_5_15cm_mean': 'hg/dm^3',
        'ocd_15_30cm_mean': 'hg/dm^3',
        'ocd_30_60cm_mean': 'hg/dm^3',
        'ocd_60_100cm_mean': 'hg/dm^3',
        'ocd_100_200cm_mean': 'hg/dm^3',
        'bdod_0_5cm_mean_1000': 'cg/cm3',
        'bdod_5_15cm_mean_1000': 'cg/cm3',
        'bdod_15_30cm_mean_1000': 'cg/cm3',
        'bdod_30_60cm_mean_1000': 'cg/cm3',
        'bdod_60_100cm_mean_1000': 'cg/cm3',
        'bdod_100_200cm_mean_1000': 'cg/cm3',
        'cec_0_5cm_mean_1000': 'mmol/kg',
        'cec_5_15cm_mean_1000': 'mmol/kg',
        'cec_15_30cm_mean_1000': 'mmol/kg',
        'cec_30_60cm_mean_1000': 'mmol/kg',
        'cec_60_100cm_mean_1000': 'mmol/kg',
        'cec_100_200cm_mean_1000': 'cm3/dm3 (vol‰)',
        'cfvo_0_5cm_mean_1000': 'cm3/dm3 (vol‰)',
        'cfvo_5_15cm_mean_1000': 'cm3/dm3 (vol‰)',
        'cfvo_15_30cm_mean_1000': 'cm3/dm3 (vol‰)',
        'cfvo_30_60cm_mean_1000': 'cm3/dm3 (vol‰)',
        'cfvo_60_100cm_mean_1000': 'cm3/dm3 (vol‰)',
        'cfvo_100_200cm_mean_1000': 'cm3/dm3 (vol‰)',
        'clay_0_5cm_mean_1000': 'g/kg',
        'clay_5_15cm_mean_1000': 'g/kg',
        'clay_15_30cm_mean_1000': 'g/kg',
        'clay_30_60cm_mean_1000': 'g/kg',
        'clay_60_100cm_mean_1000': 'g/kg',
        'clay_100_200cm_mean_1000': 'g/kg',
        'nitrogen_0_5cm_mean_1000': 'cg/kg',
        'nitrogen_5_15cm_mean_1000': 'cg/kg',
        'nitrogen_15_30cm_mean_1000': 'cg/kg',
        'nitrogen_30_60cm_mean_1000': 'cg/kg',
        'nitrogen_60_100cm_mean_1000': 'cg/kg',
        'nitrogen_100_200cm_mean_1000': 'cg/kg',
        'phh2o_0_5cm_mean_1000': 'pHx10',
        'phh2o_5_15cm_mean_1000': 'pHx10',
        'phh2o_15_30cm_mean_1000': 'pHx10',
        'phh2o_30_60cm_mean_1000': 'pHx10',
        'phh2o_60_100cm_mean_1000': 'pHx10',
        'phh2o_100_200cm_mean_1000': 'pHx10',
        'sand_0_5cm_mean_1000': 'g/kg',
        'sand_5_15cm_mean_1000': 'g/kg',
        'sand_15_30cm_mean_1000': 'g/kg',
        'sand_30_60cm_mean_1000': 'g/kg',
        'sand_60_100cm_mean_1000': 'g/kg',
        'sand_100_200cm_mean_1000': 'g/kg',
        'silt_0_5cm_mean_1000': 'g/kg',
        'silt_5_15cm_mean_1000': 'g/kg',
        'silt_15_30cm_mean_1000': 'g/kg',
        'silt_30_60cm_mean_1000': 'g/kg',
        'silt_60_100cm_mean_1000': 'g/kg',
        'silt_100_200cm_mean_1000': 'g/kg',
        'soc_0_5cm_mean_1000': 'dg/kg',
        'soc_5_15cm_mean_1000': 'dg/kg',
        'soc_15_30cm_mean_1000': 'dg/kg',
        'soc_30_60cm_mean_1000': 'dg/kg',
        'soc_60_100cm_mean_1000': 'dg/kg',
        'soc_100_200cm_mean_1000': 'dg/kg',
        'ocd_0_5cm_mean_1000': 'hg/dm^3',
        'ocd_5_15cm_mean_1000': 'hg/dm^3',
        'ocd_15_30cm_mean_1000': 'hg/dm^3',
        'ocd_30_60cm_mean_1000': 'hg/dm^3',
        'ocd_60_100cm_mean_1000': 'hg/dm^3',
        'ocd_100_200cm_mean_1000': 'hg/dm^3'
        }

class ImportAndSave(ABC):
    """Abstract class for importing FIDC formatted CSV files and saving them in a specified format.
    
    Parameters:
        input_csv: str
            Path to the input CSV file.
        out_file: str
            Path to the output file. If not provided, the output file will be saved in the same directory as the input file.
        variables: dict[str, Any]
            Mapping of variable names in the input CSV file to the desired names in the output file.
        units: dict[str, Any]
            Mapping of variable names to the desired units in the output file.
    """
    def __init__(self,
                 input_csv: str = '',
                 out_file: str = None,
                 variables: dict[str, Any] = DEFAULT_LONG_NAMES,
                 units: dict[str, Any] = DEFAULT_UNITS):
        
        self.input_csv = input_csv
        self.out_file = out_file
        self.variables = variables
        self.units = units

    @staticmethod    
    def round_to_10_degree(coord):
        return np.floor(coord / 10.0) * 10.0
    
    def compute_cube(self, 
                     variables: dict[str, Any] = 'default') -> xr.Dataset:
        """
        Compute the data cube from the input CSV file.
        
        Parameters:
            variables: dict[str, Any]
                Mapping of variable names in the input CSV file to the desired names in the output file. If not provided, the default variables will be used.
        
        Returns:
            xr.Dataset: The computed data cube.
        """
        if variables == 'default':
            var_names = DEFAULT_VARS
        
        df_ = pd.read_csv(self.input_csv)
        df_['Latitude_Cluster'] = df_['latitude'].apply(ImportAndSave.round_to_10_degree)
        df_['Longitude_Cluster'] = df_['longitude'].apply(ImportAndSave.round_to_10_degree)
        df_['cluster'] = df_['Latitude_Cluster'].astype(str) + '_' + df_['Longitude_Cluster'].astype(str)
        df_.drop(['Latitude_Cluster', 'Longitude_Cluster'], axis=1, inplace=True)
        df_['cluster'], _ = pd.factorize(df_['cluster'])
        
        sites = df_.cluster.values
        plot_ds = []
        for site in np.unique(sites):
            siteMask  = site==sites
            coords = {'cluster': [site], 'sample':np.arange(len(df_['agb'].values[siteMask]))}
            ds = {}
            for _var in var_names:
                ds[_var] = (('cluster', 'sample'), [df_[_var].values[siteMask]])
                
                	
            ds = xr.Dataset(data_vars=ds, coords=coords)  
            ds = ds.assign_coords(latitude  =  np.unique(df_['latitude'].values[siteMask]),
                                  longitude = np.unique(df_['longitude'].values[siteMask]))
            plot_ds.append(ds)    
        plot_ds = xr.concat(plot_ds, dim= 'cluster')
        
        for _var in DEFAULT_LONG_NAMES.keys():
            plot_ds[_var] = plot_ds[_var].assign_attrs(long_name=DEFAULT_LONG_NAMES[_var],
                                                       units=DEFAULT_UNITS[_var])
            
        plot_ds = plot_ds.assign_attrs(title = "Training dataset for stand age upscaling",
                                        created_by='Simon Besnard',
                                        contact = 'besnard@gfz-potsdam.de',
                                        creation_date=datetime.now().strftime("%d-%m-%Y %H:%M"))
        plot_ds.to_netcdf(self.out_file, mode='w')
        
        return plot_ds
