apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: spearth
        command:
        - /bin/bash
        - -c
        - |
          source /venv/bin/activate
          python /scripts/move_dataGCP.py
        resources:
          requests:
            memory: "20000Mi"
            cpu: "1000m"
          limits:
            memory: "20000Mi"
            cpu: "1000m"
        volumeMounts:
        - mountPath: /data/
          subPath: mover
          name: nfs-storage
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: mover-pvc
          readOnly: false
