apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: modis-gapfiller-pv
  resources:
    requests:
      storage: 1Ti
